name: Steel Price Checker

on:
  schedule:
    - cron: "30 4 * * *"    # ۸:۰۰ صبح ایران (۴:۳۰ UTC)
    - cron: "30 8 * * *"    # ۱۲:۰۰ ظهر ایران (۸:۳۰ UTC)  
    - cron: "30 12 * * *"   # ۱۶:۰۰ عصر ایران (۱۲:۳۰ UTC)
    - cron: "30 16 * * *"   # ۲۰:۰۰ شب ایران (۱۶:۳۰ UTC)
    - cron: "30 20 * * *"   # ۴:۰۰ بامداد ایران (۲۰:۳۰ UTC)
  workflow_dispatch:

jobs:
  check-prices:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
            - name: Install dependencies
        pip install -r requirements.txt 
        pip install requests beautifulsoup4 python-telegram-bot jdatetime

    - name: Run price checker
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python steel_scraper.py
