name: Steel Price Checker

on:
  schedule:
    - cron: "30 4 * * *"
    - cron: "30 8 * * *"
    - cron: "30 12 * * *"
    - cron: "30 16 * * *"
  workflow_dispatch:

jobs:
  check-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run price checker
        run: python steel_scraper.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
