Ø±name: Steel Price Checker Selenium

on:
  schedule:
    - cron: "30 4 * * *"
    - cron: "30 8 * * *"
    - cron: "30 12 * * *"
    - cron: "30 16 * * *"
  workflow_dispatch:

jobs:
  check-prices:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Run price checker
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python steel_scraper.py
